# a docker compose file for mysql and adminer with a volume for the database and setup for environment variables

version: "3.1"
services:
  db1: # Define the first database service
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: akashaurcode
      MYSQL_DATABASE: akashDB1 # Unique database name for this instance
      MYSQL_USER: akash # Unique user for this database
      MYSQL_PASSWORD: akash
    ports:
      - 33061:3306 # Map to a different port to avoid conflicts
    volumes:
      - ./mysql1:/var/lib/mysql # Unique volume for data persistence

  db2: # Define the second database service (add more as needed)
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: akashaurcode
      MYSQL_DATABASE: akash2DB2 # Unique database name
      MYSQL_USER: akash2 # Unique user
      MYSQL_PASSWORD: akash2
    ports:
      - 33062:3306 # Map to a different port
    volumes:
      - ./mysql2:/var/lib/mysql # Unique volume

  adminer: # Adminer service remains as is
    image: adminer
    restart: always
    ports:
      - 8080:8080
